name: Build News sdk payload

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  payload-build-OldSDK:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install xxd clang-15 lld-15

    - name: Install toolchain
      run: |
        wget https://github.com/ps5-payload-dev/sdk/releases/download/v0.26.2/ps5-payload-sdk.zip
        sudo unzip -qq ps5-payload-sdk.zip -d /

    - name: Build
      run: PS5_PAYLOAD_SDK=/ps5-payload-sdk make

    - name: Attest
      uses: actions/attest-build-provenance@v1
      continue-on-error: true  # this will fail if the repo is private
      with: 
        subject-path: ./bin/ps5-self-decrypter.elf

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ps5-self-decrypter
        path: ./bin/ps5-self-decrypter.elf
        if-no-files-found: error